### ISSUE TITLE
Using getlogin() is problematic

### ISSUE THREAD

**Issue by eserte** [Grinnz/Path-ExpandTilde#1]
On some of my smokers the test suite fails:
```
#   Failed test '~username expands to home dir'
#   at t/tilde.t line 19.
#          got: '/usr/home/eserte'
#     expected: '/usr/home/cpansand'
# Looks like you failed 1 test of 17.
t/tilde.t .............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/17 subtests 
```

It seems that the problem is that `getlogin` is used to get the current user. This function does not return the right thing if the session was created with `sudo`. It seems that it's better to use `getpwuid($<)` instead.

Here some examples:
```
# bad (if sudo is used):
$ perl -E 'say getlogin'           
eserte
$ sudo perl -E 'say getlogin'
eserte
# good
perl -E 'say scalar getpwuid($<)'
eserte
$ sudo perl -E 'say scalar getpwuid($<)'
root
```

**Comment by Grinnz** [comment]
getpwuid is not implemented on Windows, hence trying getlogin first. I can add a check to make sure that it matches getpwuid if that's defined.

**Comment by Grinnz** [comment]
Hopefully the changes in https://github.com/Grinnz/Path-ExpandTilde/commit/c2a150a7010ecdfe8d483e83222da1c9a7ed359b should behave better. Thanks for the report.

**Comment by Grinnz** [comment]
This looks resolved. http://fast-matrix.cpantesters.org/?dist=Path-ExpandTilde%200.002
